### ISSUE TITLE
Updating url-mapper

### ISSUE THREAD

**Issue by christianalfoni** [itaylor/redux-action-router#1]
Hi there!

@Guria and I are discussing to update the url-mapper with a breaking change. Instead of `urlMapper` mapping to a function and running it, it will return the function instead.

So:

``` js
   urlChangeSupport.on('change', (url) => {
      url = hashOnly(url);
      urlMapper(url, urlDispatchMap);
    });
```

Will become something like:

``` js
   urlChangeSupport.on('change', (url) => {
      const path = hashOnlyPath(url);
      const route = urlMapper(path, urlDispatchMap); // Only pass the path
      route && route();
    });
```

We are also planning to remove the query handling of url-mapper. The reason is that queries are not necessary to map to the correct function. That way we can reduce the scope of url-mapper and give more freedom. So passing queries would be:

``` js
   urlChangeSupport.on('change', (url) => {
      const path = hashOnlyPath(url);
      const query = query(url);
      const route = urlMapper(path, urlDispatchMap);
      route && route({
        path,
        query,
        url
      });
    });
```

So now you can customize what you actually want to pass to the function. Maybe you do not want to support querystrings... it is not very common to use them. Just drop them out. Or use the `querystring` library to parse it. It is also easier to handle baseUrl as you will only pass a path into url-mapper to figure out what to trigger.

Any thoughts on this? We wanted to bring it by you first :-)

**Comment by itaylor** [comment]
Hi @christianalfoni, I'm definitely supportive of the idea of making url-mapper do less and only do the path matching part. I'm not currently making use of query parameters, so dropping the use of them query parameters from url-mapper is no problem, and as you said, it's easy to parse them out later.

My main concern with the proposed changes are that it appears that after this change, the parsed path parameter object would not be returned from url-mapper.  They are currently passed as `params` when url-mapper calls the route function.  I need them, as I use them as the payload that gets passed to my route function.  I'm sure I could re-parse them from the path again, but considering that url-mapper is probably going to have parse them to do the match anyways, it seems wasteful to have to do that parsing twice. 

Maybe something like this could solve that case as well?

```
  urlchangeSupport.on('change', (url) => { 
     const path = hashOnlyPath(url);
     const {route, params} = urlMapper(path, urlDispatchMap);
     route && route({params});
  }
```

Another thing I like about the concept of url-mapper not calling the functions is that the object passed to url-mapper would no longer need to be JS Object that is used as a `Map<String,Function>`, since url-mapper isn't going to call the route function it could be a `Map<String, Any>`, which provides more flexibility.

**Comment by christianalfoni** [comment]
Thanks for the input @itaylor!

Sorry, I was a bit fast on handling params. I thought we could use "partial application" or whatever it is called. So:

``` js
var route = urlMapper(path, {
  '/messages/:id': function (params, query, options) {

  }
});

route && route(parsedQuery, myOptions);
```

So the first argument is always params. But that does not fit well with using something else than functions. I like that idea too. Hm hm... it is of course less mindpower to just return the params and the value of the mapper.

So, as you stated:

``` js
  urlchangeSupport.on('change', (url) => { 
     const path = hashOnlyPath(url);
     const {route, params} = urlMapper(path, urlDispatchMap);
     route && route({params});
  }
```

I like that one too. What do you think @Guria?
